### ISSUE TITLE
Comprobar casos extraños "Autoreply".

### ISSUE THREAD

**Issue by CeuxDruman** [DPIRPSG/DP11Entrega#39]
Cosas que se me han ocurrido que podrían ser conflictivas (no las he probado, sólo las documento para que puedas probarlas detenidamente):
-Si pongo 2 veces la misma palabra en 1 autoreply... ¿Se me envío 2 veces en mensaje o funciona bien y no tiene ningún efecto secundario?
-Si pongo "pc", pero el otro escribe "PC"... ¿No funciona el autoreply? (Debería funcionar, y si no lo hace la solución es: a la hora de comparar mensaje con autoreply transformar ambos a toLowerCase (minúsculas) y entonces compararlos).

PD: Los probaré en mis casos de pruebas, es por si querías probarlo y asegurarte antes.

**Comment by ManuelLR** [comment]
- Poner 2 veces una palabra en un autoreply no afecta en absolutamente nada ya que el mecanismo puesto en código coge el texto del mensaje y le pregunta por cada palabra del autoreply por lo que si aparece dos veces no pasa absolutamente sea en el autoreply o en el mensaje.
- Lo de mayúsculas ya lo había tenido en cuenta y no sucede (no recuerdo si pone todo en minúsculas o mayúsculas

**Comment by ManuelLR** [comment]
Te lo reasigno para que compruebes todo y si quieres puedes cerrarlo
