### ISSUE TITLE
¡Al firmar un Match la firma no tiene el formato correcto!

### ISSUE THREAD

**Issue by CeuxDruman** [DPIRPSG/DP11Entrega#58]
Listas tus Matchs, le das a firmar a uno, se recarga la página y te muestra la fecha de la firma en la columna correspondientes pero con un formato inadecuado. Si recargas (vas otra vez a la vista desde el menú), ya aparece con el formato adecuado.

**Comment by migrodcab** [comment]
Listo, solo falta confirmacion por parte de Carlos @518543fa8d0593173b42c103c61e5b84a7493f01
