### ISSUE TITLE
Cancelado "true/false" no traducido en listados de Barter y Match

### ISSUE THREAD

**Issue by CeuxDruman** [DPIRPSG/DP11Entrega#59]
En ambos listados en español sigue poniendo "true" o "false".

Yo con Cerrar puse "Sí/No" o "Yes/No" según el idioma y si estaba a true o false. En Cancelar podemos hacerlo como queráis, pero si no ponmos Sí/No, al menos que ponga "verdadero" "falso" (Que para mi gusto es una horrible traducción de si algo está cancelado).

**Comment by migrodcab** [comment]
Listo, falta confirmación @4da4380977972172055a8d4f6970fdf4a55f9c7b
